### ISSUE TITLE
Define our use-case - reference implementation for the hackathon

### ISSUE THREAD

**Issue by positonic** [PANDR-Berlin/licenseforgood#2]

**Comment by jamespfarrell** [comment]
[Jean's work](https://docs.google.com/presentation/d/1VseVyKk5YeuWbUV7nZ_nqrM4B6MJbdMmW9vc9SjCOEc/edit?usp=sharing) in useful, and includes and idea for a use case.

**Comment by Chmarusso** [comment]
After a short talk with James, here is some idea for use-case we can implement: 

NGO can create a programme/charity event in our system.  Each programme has voluntary work or actions that can be executed by local volunteers (water a plant, deliver stuff, clean up the place). Voluntary work can be represented by NFT token which represents: volunteer, type of work, and supporter. Supporters from all over the world can "buy" NFT token using a smart contract. The friction of money goes to volunteer and NGO once work is mark as done by NGO. 

The social badge is owned by each supporter and it represents all NFT tokens that supporter "bought".

Pros: 
- supporter has a social badge that he can show off to everyone 
- supporter and volunteer can be connected with each other and create some relation 
- NGO receives money for each action 
- volunteer receives money for each action 
- cash flow is controlled by smart contract and it is transparent to all 
- supporters can be more involved in helping because they precisely see who and how spent their money  

What we need from the technical side:
- web app for creating charity events and specifying actions that volunteers can do
- logic for creating NFT
- smart contract for cash handling (cannot do it with Tupelo)

**Comment by jamespfarrell** [comment]
I have created 2 other use case examples here:

[Zero deforestation badge](https://github.com/LicenseRocks/licenseforgood/blob/master/UseCaseProposal-ZeroDeforestationBadge.md)

[Carbon Neutral bade in partnership with Masarang foundation](https://github.com/LicenseRocks/licenseforgood/blob/master/UseCaseProposalCarbonNeutralityBadge.md)

I would encourage everyone to document their ideas for use cases, so that we can give each other feedback and have our ideas ready for the call on Wednesday!?

**Comment by Chmarusso** [comment]
Cool, I posted another use case with some description: https://github.com/LicenseRocks/licenseforgood/blob/master/Tokenize-Voluntary-Work.md
